# Generated by Django 2.1.5 on 2019-01-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='flighttime',
        ),
    ]
