# Generated by Django 2.1.5 on 2019-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_flighttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='photo',
            field=models.ImageField(default='../static/images/not_found2.jpg', upload_to='flights/%Y', verbose_name='Картинка рейса'),
        ),
    ]
